/// Represents a single entry in the kernel's symbol table.
pub struct KernelSymbol {
    pub addr: usize,
    pub name: &'static str,
}

// The actual symbol table is generated by build.rs at compile time
// based on the kernel's symbol map (generated via nm -n).
include!(concat!(env!("OUT_DIR"), "/generated_symbols.rs"));

/// Resolves a memory address to the closest preceding function name.
pub fn resolve(addr: usize) -> Option<(&'static str, usize)> {
    if KERNEL_SYMBOLS.is_empty() { return None; }

    // Use binary search for O(log n) lookup.
    // KERNEL_SYMBOLS must be sorted by address (handled by 'nm -n').
    match KERNEL_SYMBOLS.binary_search_by_key(&addr, |s| s.addr) {
        Ok(idx) => Some((KERNEL_SYMBOLS[idx].name, 0)),
        Err(idx) => {
            // idx is the insertion point. The closest preceding symbol is at idx - 1.
            if idx == 0 {
                None
            } else {
                let s = &KERNEL_SYMBOLS[idx - 1];
                let offset = addr - s.addr;
                // Heuristic: If offset is > 64KB, it's likely not the same function.
                if offset < 0x10000 {
                    Some((s.name, offset))
                } else {
                    None
                }
            }
        }
    }
}