[package]
name = "kernel"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
drivers = { path = "../drivers" }
gui = { path = "../gui" }
lib = { path = "../lib" }
common = { path = "../common" }

[lib]
crate-type = ["staticlib"]

[[bin]]
name = "kernel"
path = "src/lib.rs"
