[build]
target = "x86_64-unknown-none"
host = "x86_64-pc-windows-gnu"

[target.x86_64-unknown-none]
linker = "rust-lld"
rustflags = [
    "-C", "link-arg=-T",
    "-C", "link-arg=kernel/x86_64/link.ld",
    "-C", "target-feature=-mmx,-sse",
    "-C", "no-redzone=y",
]

[target.i686-unknown-none]
linker = "rust-lld"
rustflags = [
    "-C", "link-arg=-T",
    "-C", "link-arg=kernel/x86/link.ld",
    "-C", "target-feature=-mmx",
    "-C", "no-redzone=y",
]

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

[target.i686-pc-windows-gnu]
linker = "i686-w64-mingw32-gcc"
