name: NebulaOS Build

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y grub-pc-bin xorriso qemu-system-i386

      - name: Add custom target
        run: rustup target add i686-unknown-none

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build kernel + ISO
        run: make iso

      - name: Upload kernel artifact
        uses: actions/upload-artifact@v4
        with:
          name: nebula-kernel
          path: target/i686-unknown-none/debug/nebula_os

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: nebula-os-iso
          path: nebula_os.iso
